services:
  reth3:
    image: ghcr.io/paradigmxyz/reth:v1.4.1
    container_name: reth3
    volumes:
      - ./rethdata/3:/data/reth/execution-data
      - ./assets:/root/assets/
    ports:
      - "38545:8545"
      - "38551:8551"
      - "9103:9001"
      - "60303:50303"
      - "60303:50303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/root/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=50303"
      - "--port=50303"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--txpool.gas-limit=300000000" # default * 10
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
